### ISSUE TITLE
mixin.unstream.player_movement makes shields not work

### ISSUE THREAD

**Issue by VindSole** [Tater-Certified/Potatoptimize#18]
Title basically, moreover while testing I kept crashing every time I tried to create a world with only this mod and Fabric API, I don't know if that's a bug or issue on my end.

**Comment by QPCrummer** [comment]
Thank you for reporting this issue! I haven’t tested creating a world since I typically just use the same world and generate some new chunks. I would think it would practically be the same thing, but I guess not. 

I’ll fix this as soon as I am not busy.

**Comment by VindSole** [comment]
Quick update, shield blocking stopped working again, and now I have disabled almost all mixins but issue persists, only way to fix is to remove the mod.

**Comment by QPCrummer** [comment]
If you disable every mixin, then it must not be my mod. I only change code via the mixins within my mod, and every one of these mixins can be disabled. There are no hidden optimizations. In theory, Fabric API has broken the game in the past, so technically it could be that. Also don’t put it past Mojang to break their own game too :p

**Comment by QPCrummer** [comment]
This issue has been fixed in the latest version. Please test to make sure that the bug is fixed: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.4

**Comment by QPCrummer** [comment]
The bug has been verified to be fixed in the latest version. I will now close this issue as resolved.
