### ISSUE TITLE
Crashes upon loading world when mixin.random.world is enabled

### ISSUE THREAD

**Issue by Maoijoon** [Tater-Certified/Potatoptimize#19]
Tested on 0.0.1-dev.3 for 1.21.
When mixin.random.world is enabled and Faster Random is not installed, the game crashes when attempting to create or load a world on the server side. Only Fabric API and Potatoptimize are installed. Switching JVMs (OpenJDK, GraalVM EE, OpenJ9) doesn't work, nor does removing any flags that I've set.
[crash_log.txt](https://github.com/user-attachments/files/16116818/crash_log.txt)

**Comment by QPCrummer** [comment]
I have fixed the issue and will release a new version today. Thank you for reporting this

**Comment by QPCrummer** [comment]
This has been fixed in this release. Please test to make sure it is properly fixed: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.4

**Comment by Maoijoon** [comment]
Fixed! Closing.
