### ISSUE TITLE
Undocumented mixins, including one that breaks shields

### ISSUE THREAD

**Issue by Maoijoon** [Tater-Certified/Potatoptimize#20]
As of posting this issue, there are 5 mixins in version 0.0.1-dev.3 that are completely undocumented, both on the wiki and on any other issue. They are:
`mixin.fastmath.general`
`mixin.fastmath.vec`
`mixin.feature.interaction_limiter`
`mixin.unstable.explosion_throttle`
`mixin.unstable.sound`
I found these when reading through #18 with the same issue. I disabled all the documented mixins and removed every mod except for Fabric API and Potatoptimize, but shields still didn't work. I looked in `potatoptimize.mixins.json` and read through the list of mixins to see if there were any missing on the wiki, and those above are the ones I found. Through trial and error, I figured out `mixin.fastmath.vec` is the one causing the issue, as disabling it, and only it, allowed the shields to work again.
As for the others, I can probably figure out what some of these do myself, but a brief explanation as to what they do (or even just a mention on the wiki of their existence) would be appreciated.

**Comment by QPCrummer** [comment]
Yeah, I pushed a lot of things right before going on vacation and didn't document anything. That's completely my fault. I'll get to updating the wiki and fixing the shield issue. Thanks for reporting this!

**Comment by Maoijoon** [comment]
Thank you for the quick response!
I did some more testing with this mod and found another, more serious bug with another previously undocumented mixin. When `mixin.fastmath.general` is enabled, running the `/locate biome` command will cause a catastrophic memory leak, crashing the game in seconds. This only happens with biomes; structures and points of interests seem to be unaffected.
Here's the crash log, if it helps: [crash_locate.txt](https://github.com/user-attachments/files/16117451/crash_locate.txt)
Fantastic work so far, by the way. This mod, in combination with a few others, has helped me get <2 MSPT on singleplayer worlds with a 12 chunk render/simulation distance, which I wouldn't have dreamed of before on my crummy laptop.

**Comment by QPCrummer** [comment]
All mixins you mentioned are now documented.

Additionally the shield issue has been fixed in the latest version. Please test this to ensure it is properly fixed: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.4

**Comment by Maoijoon** [comment]
Fixed! Closing.
