### ISSUE TITLE
mixin.random.generators stalls the server when using /locate mansion

### ISSUE THREAD

**Issue by VindSole** [Tater-Certified/Potatoptimize#22]
When mixin.random.generators is enabled, using /locate to find a mansion freezes the world and cannot leave the world unless game is forcibly closed, probably happens with other structures set far away from the player.

Additionally, worlds fail to load and crash when mixin.random.generators is disabled but mixin.random.math is enabled, the former has to be enabled or both disabled to not crash.

**Comment by QPCrummer** [comment]
This is a rather odd issue. The /locate command shouldn’t even use random. Is there an error that is produce in the logs that you could share here?

**Comment by VindSole** [comment]
Tested on a fresh instance but log doesn't output anything after using /locate mansion, on my modded instance it does output something, both were stuck on "saving world" so I had to kill the app.

Modded
[latest.log](https://github.com/user-attachments/files/16147410/latest.log)

Only this mod
[latest.log](https://github.com/user-attachments/files/16147429/latest.log)

**Comment by QPCrummer** [comment]
This issue should be fixed in the latest version: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.5

Can you please test to confirm this?

**Comment by VindSole** [comment]
Fixed, sorta, I just used /locate biome basalt_deltas in the nether and it randomly crashed after a few seconds, I don't know if it related because it crashes when relevant optimizations are disabled.

**Comment by QPCrummer** [comment]
This looks like an insanely bad memory leak. It just ate through all 16GB of my dedicated memory in about 4 seconds. Yikes. I'll need to go through the optimizations one by one to see what is causing it

**Comment by QPCrummer** [comment]
Ok, I fixed the issue. It will be included in the next release

**Comment by QPCrummer** [comment]
I should be fixed in this version. Can you please test it and make sure it is: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.6

**Comment by VindSole** [comment]
Seems fixed, thanks!

**Comment by QPCrummer** [comment]
Amazing! Thanks for reporting it!
