### ISSUE TITLE
Crash with C2ME on server causing by Maps

### ISSUE THREAD

**Issue by yichifauzi** [Tater-Certified/Potatoptimize#25]
Minecraft Version : 1.21
Fabric Version: 0.15.11
Fabric API Version : 0.100.6
Potatooptimize Version : Potatoptimize 0.0.1 Dev 6 (1.21)
C2ME Version : 0.2.0+alpha.11.107 devbuild for 1.21

Problem :
Client side :
When using in singleplayer will just show blank map

![image](https://github.com/user-attachments/assets/d5fea0ab-032e-4621-9053-c762038397f0)

Server side:
When using in server will causing player to kick out server

Logs:  https://mclo.gs/e7kloPS

![image](https://github.com/user-attachments/assets/b6abe0bb-6a06-4c34-90bc-dcd019d13ae5)

**Comment by QPCrummer** [comment]
Can you try putting this into the config and seeing if it fixes the issue: mixin.item.map_chunk_loading = false

**Comment by yichifauzi** [comment]
> Can you try putting this into the config and seeing if it fixes the issue: mixin.item.map_chunk_loading = false

Yeah it work fine

**Comment by QPCrummer** [comment]
Ok, I’m not sure if it’s something I’ll be able to fix since C2me changes so much in terms of chunk loading. I’ll probably just have to disable it automatically when C2me is present. Thanks for finding this!

**Comment by QPCrummer** [comment]
It should be fixed in this version: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.7
