### ISSUE TITLE
Mixin conflict with nox-renoxed

### ISSUE THREAD

**Issue by unix-supremacist** [Tater-Certified/Potatoptimize#26]
built nox renoxed from [this pr](https://github.com/qxeii/nox-renoxed/pull/28)

https://pastebin.com/nu0RNX6K

extra note, this can be temporarily fixed by disabling the potatooptimize mixin

**Comment by QPCrummer** [comment]
This is probably fixed in the next version. It had a similar issue with another mod

**Comment by QPCrummer** [comment]
See if your issue is fixed in this version: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.7

**Comment by unix-supremacist** [comment]
yep :+1:
