### ISSUE TITLE
Incompatible with Silk

### ISSUE THREAD

**Issue by sternschnaube** [Tater-Certified/Potatoptimize#30]
https://pastebin.com/raw/SPzdU0di

https://modrinth.com/mod/silk

Worked fine, had issues and had to stop the server. Afterwards this came up.

**Comment by QPCrummer** [comment]
If you really want the async I/O, I'd just recommend installing c2me. While I'm going to improve the implementation I have right now, c2me will perform significantly better, and probably be more compatible as well. I let you know when I have my new implementation in place

**Comment by sternschnaube** [comment]
I'm testing C2ME from time to time, gives me headaches sometimes.

I need Silk for Veinminer mod.
https://modrinth.com/datapack/veinminer

Thanks for the upcoming fix 😊

**Comment by QPCrummer** [comment]
This probably won't be a fix unless I can remove my Overwrite (which is the current issue).

**Comment by QPCrummer** [comment]
I believe I fixed the compatibility with Silk, however I am not confident that silk will save data properly. It will save all of its data when the server closes, but it may not save its data when the world saves. It's not really something I can get around, but at least silk shouldn't crash when paired with potatoptimize.
