### ISSUE TITLE
crash on startup with lithium

### ISSUE THREAD

**Issue by Mr-Squid42** [Tater-Certified/Potatoptimize#33]
crash with lithium version 0.13.0

https://gist.github.com/Mr-Squid42/ae528d2a41c5f822c0d694cddcee8062

i've determined the crash happens when mixin.threading.explosions is set to true

**Comment by QPCrummer** [comment]
Hello. Lithium recently changed their tnt explosion exposure optimization, and that is the cause of this. Currently I have stepped down from Minecraft modding, so you may have to wait for a PR by someone to fix this, or if I ever come back, I can fix this. As of right now, all of my mods are considered abandoned until someone takes over leadership of the organization.

**Comment by Mr-Squid42** [comment]
ok
