### ISSUE TITLE
Incompatible with lithium

### ISSUE THREAD

**Issue by Rad586** [Tater-Certified/Potatoptimize#7]
**Game version:** fabric 1.19.2, fabric loader 0.15.11, fabric api 0.77.0
**Mod version:** Potatoptimize: 0.0.1 dev build 2; Lithium 0.11.1
**Description:** If `mixin.chunk.no_validation = false` in lithium wasn't disabled, the game will crash on entering world.
**Log:** https://gist.github.com/Rad586/161e705a995f8a2b91193b7f654a4d37

**Comment by QPCrummer** [comment]
More than likely Lithium optimizes the exact same thing as me. I’ll prioritize lithium’s optimization over mine as I know lithium’s doesn’t alter vanilla parity. I’ll fix this in a few minutes. Thanks for reporting it

**Comment by QPCrummer** [comment]
Can you try this version and see if the issue is fixed https://modrinth.com/mod/potatoptimize/version/9VX15rHp

**Comment by Rad586** [comment]
It's fixed, thanks for the quick fix!
